version: '3.8'

services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8085:8085"
    environment:
      - PORT=:8085
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/todo?sslmode=disable&search_path=todo
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    
  tbls:
    image: ghcr.io/k1low/tbls:latest
    volumes:
      - .:/work
    working_dir: /work
    command: doc postgres://postgres:postgres@postgres:5432/todo?sslmode=disable&search_path=todo
    profiles:
      - tbls

volumes:
  postgres_data: 
